"""org sender_name

Revision ID: 6e5c5632dd12
Revises: e3a3906b9bb4
Create Date: 2026-07-22 20:20:21.921520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e5c5632dd12'
down_revision: Union[str, Sequence[str], None] = 'e3a3906b9bb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('sender_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'sender_name')
    # ### end Alembic commands ###
