"""analytics: message variant and reply attribution

Revision ID: 926ce4307f80
Revises: cee98aac92aa
Create Date: 2026-07-22 21:34:38.480152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '926ce4307f80'
down_revision: Union[str, Sequence[str], None] = 'cee98aac92aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation_messages', sa.Column('replied_after_step', sa.Integer(), nullable=True))
    op.add_column('outreach_messages', sa.Column('variant', sa.String(length=32),
                  nullable=False, server_default='v1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outreach_messages', 'variant')
    op.drop_column('conversation_messages', 'replied_after_step')
    # ### end Alembic commands ###
