"""bounce handling, google-broken, email verification

Revision ID: cee98aac92aa
Revises: 6e5c5632dd12
Create Date: 2026-07-22 20:52:59.578541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cee98aac92aa'
down_revision: Union[str, Sequence[str], None] = '6e5c5632dd12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default supplies a value for any existing rows; the app models
    # set their own defaults on new inserts.
    op.add_column('google_credentials', sa.Column('broken', sa.Boolean(),
                  nullable=False, server_default=sa.text('0')))
    op.add_column('google_credentials', sa.Column('broken_reason', sa.String(length=255), nullable=True))
    op.add_column('google_credentials', sa.Column('broken_notified', sa.Boolean(),
                  nullable=False, server_default=sa.text('0')))
    op.add_column('outreach_messages', sa.Column('send_attempts', sa.Integer(),
                  nullable=False, server_default=sa.text('0')))
    op.add_column('outreach_messages', sa.Column('last_error', sa.String(length=500), nullable=True))
    # Grandfather any pre-existing users as verified; new signups default to
    # unverified via the model default.
    op.add_column('users', sa.Column('email_verified', sa.Boolean(),
                  nullable=False, server_default=sa.text('1')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_verified')
    op.drop_column('outreach_messages', 'last_error')
    op.drop_column('outreach_messages', 'send_attempts')
    op.drop_column('google_credentials', 'broken_notified')
    op.drop_column('google_credentials', 'broken_reason')
    op.drop_column('google_credentials', 'broken')
    # ### end Alembic commands ###
