"""lead research and org research toggle

Revision ID: e3a3906b9bb4
Revises: 3303806b239a
Create Date: 2026-07-22 20:01:18.863439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3a3906b9bb4'
down_revision: Union[str, Sequence[str], None] = '3303806b239a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('research_notes', sa.Text(), nullable=True))
    op.add_column('leads', sa.Column('research_sources', sa.JSON(), nullable=True))
    op.add_column('leads', sa.Column('researched_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('organizations', sa.Column('research_enabled', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'research_enabled')
    op.drop_column('leads', 'researched_at')
    op.drop_column('leads', 'research_sources')
    op.drop_column('leads', 'research_notes')
    # ### end Alembic commands ###
